---
version: '3'
services:
  freqtrade:
   # image: freqtradeorg/freqtrade:stable
    image: freqtradeorg/freqtrade:develop
    #Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
   # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade2/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:4270:4270"
    # Default command used when running `docker compose up`
    command: >
      trade 
      --dry-run-wallet 200
      --config /freqtrade2/user_data/mgm-config.json
      --config /freqtrade2/user_data/mgm-config-hyperopt.json
      --strategy MoniGoManiHyperStrategy